import pandas as pd
import csv
import os
import sys
import time
from datetime import datetime

if sys.stdout.encoding.lower() != 'utf-8':
    sys.stdout.reconfigure(encoding='utf-8')

def save_with_golden_schema(df, file_path):
    """Enforce that the DataFrame contains exactly the golden columns in the correct order,
    filling missing columns with NaN/blanks, and save as CSV."""
    if df is None:
        df = pd.DataFrame(columns=['Symbol'])
    
    golden_cols = [
        'Symbol', 'Name', 'Combined_Score', 'Conviction', 'Tech_Score',
        'Stage', 'Mansfield_RS', 'Daily_RSI', 'Daily_ADX',
        'EMA_Stack', 'Above_200DMA', 'Dist_52WH_pct', 'Vol_RelAvg',
        'ROE %', 'ROCE %', 'Debt to equity', 'Promoter holding %', 'Div Yld %',
        'Qtr Profit Var %', 'Qtr Sales Var %', 'Mar Cap Rs.Cr.',
        'CMP Rs.', 'P/E', 'Volume', 'Hybrid_Catalyst', '%Chg',
        'Minervini_Score', 'Piotroski_Score', 'Overall_Rating', 'Overall_Grade',
        'Delivery_Pct', 'Futures_OI_Chg_Pct'
    ]
    
    out_df = df.copy()
    
    # Normalize Symbol
    if 'Symbol' not in out_df.columns:
        actual_sym_col = next((c for c in out_df.columns if c.lower() in ['symbol', 'nsecode']), None)
        if actual_sym_col:
            out_df.rename(columns={actual_sym_col: 'Symbol'}, inplace=True)
            
    # Ensure all columns exist
    for col in golden_cols:
        if col not in out_df.columns:
            if col in ['Symbol', 'Name', 'Stage', 'EMA_Stack', 'Hybrid_Catalyst', 'Overall_Grade']:
                out_df[col] = None
            else:
                out_df[col] = float('nan')
            
    # Order them
    out_df = out_df[golden_cols]
    
    try:
        # Atomic write (tmp+os.replace) — a crash mid-write used to leave a torn
        # FINAL_*.csv that read back empty/partial and corrupted board rankings.
        from io_utils import atomic_write_text
        atomic_write_text(file_path, out_df.to_csv(index=False))
        return True
    except PermissionError:
        print(f"\n❌ [ERROR] Could not write to {file_path} because it is currently OPEN in another program (like Excel). Please close it!")
        return False


# ==========================================
# CONFIGURATION
# ==========================================
MASTER_FILE = 'MASTER_scan_results.csv'

TARGETS = [
    # ── STAGE 2 TARGETS (Normal Market) ──────────────────────────────────────
    {
        "tech_file": "Stage2_Hunter.csv",
        "output_file": "FINAL_Hunter_Picks.csv",
        "name": "Stage 2 Hunter",
        "mode": "stage2"
    },
    {
        "tech_file": "Stage2_Pullback.csv",
        "output_file": "FINAL_Pullback_Picks.csv",
        "name": "Stage 2 Pullback",
        "mode": "stage2"
    },
    {
        "tech_file": "Early_Birds.csv",
        "output_file": "FINAL_EarlyBird_Picks.csv",
        "name": "Early Birds",
        "mode": "stage2"
    },
    {
        "tech_file": "Strong_Leaders.csv",
        "output_file": "FINAL_Leader_Picks.csv",
        "name": "Strong Leaders",
        "mode": "stage2"
    },

    # ── RECOVERY PHASE TARGETS (Post-Shock Apr-2026) ──────────────────────────
    # fund_file: dedicated Screener.in CSV (has Debt/Equity, Promoter Holding, ROCE)
    # Generated by screener_processor.py from the Recovery_* HTML pages.
    {
        "tech_file":  "Recovery_RS_Survivors.csv",
        "output_file": "FINAL_Recovery_RSLeaders.csv",
        "name": "RS Survivors",
        "mode": "recovery",
        "fund_file": "SCREENER_Recovery_RSLeaders.csv"
    },
    {
        "tech_file":  "Recovery_Climax_Bounce.csv",
        "output_file": "FINAL_Recovery_ClimaxBounce.csv",
        "name": "Climax Bounce",
        "mode": "recovery",
        "fund_file": "SCREENER_Recovery_ClimaxBounce.csv"
    },
    {
        "tech_file":  "Recovery_Early_Birds.csv",
        "output_file": "FINAL_Recovery_EarlyBirds.csv",
        "name": "Recovery Early Birds",
        "mode": "recovery",
        "fund_file": "SCREENER_Recovery_EarlyBirds.csv"
    },
]

# ==========================================
# CONVICTION LOGIC — STAGE 2 (Normal Market)
# Rewards high earnings growth, sales growth, ROE, and small/mid-cap bias.
# ==========================================
def _safe_num(row, *keys, default=0.0):
    """Parse the first present, parseable value among `keys` from a row.

    RANKING-INTEGRITY FIX (19 Jun 2026): the conviction scorers previously
    wrapped their ENTIRE body in `try/except: pass`, so a single unparseable
    cell ('N/A', '-', None) raised on the first field and aborted ALL remaining
    additions — silently collapsing conviction toward the 5.0 base and skewing
    Combined_Score. This helper isolates each field: one bad cell yields 0 for
    THAT field only, never aborting the rest.
    """
    for k in keys:
        if k not in row:
            continue
        v = row.get(k)
        if v is None:
            continue
        s = str(v).replace(',', '').strip()
        if s.lower() in ('', 'nan', 'n/a', 'na', '-', '--', 'none'):
            continue
        try:
            return float(s)
        except (TypeError, ValueError):
            continue
    return default


# T2.4 (20 Jun 2026): the v1 bull conviction below uses ONLY growth + ROE + mcap.
# Now that Screener.in premium reliably supplies D/E, ROCE, promoter holding and
# dividend yield, the v2 scorer (_calc_conviction_v2) also rewards balance-sheet
# quality and founder backing — while keeping growth dominant (Minervini profile).
# It is GATED behind BULL_CONVICTION_V2 (default OFF) and must clear a validation.py
# backtest before becoming the default (per the "validate before changing signals"
# rule). Flip with: set BULL_CONVICTION_V2=1.
_BULL_CONV_V2 = os.getenv("BULL_CONVICTION_V2", "0").strip().lower() in ("1", "true", "yes", "on")


def _adjust_conviction_by_nse_metrics(row, score):
    # 1. Delivery_Pct adjustments (applicable to all equity cash stocks)
    del_val = _safe_num(row, 'Delivery_Pct', default=None)
    if del_val is not None:
        if del_val >= 50.0:
            score += 0.5  # Heavy institutional accumulation
        elif del_val < 35.0:
            score -= 0.5  # Weak institutional accumulation on breakout

    # 2. Futures_OI_Chg_Pct adjustments (only if F&O listed and populated)
    oi_val = _safe_num(row, 'Futures_OI_Chg_Pct', default=None)
    if oi_val is not None:
        pct_chg = _safe_num(row, '%Chg', 'Change %', default=0.0)
        # If OI rises on a positive breakout day, it's a Long Build-up (Bullish)
        if oi_val > 0.0:
            if pct_chg >= 0.0:
                score += 0.5  # Long Build-up
            else:
                score -= 0.5  # Short Build-up (rising short interest)
        elif oi_val < 0.0:
            if pct_chg >= 0.0:
                score -= 0.5  # Long Unwinding (weakness)
            else:
                score += 0.5  # Short Covering (bullish covering)
    return score


def _calc_conviction_v2(row):
    """Bull conviction v2 — growth-primary + now-reliable quality signals.
    Max caps at 10, but reaching the top now requires BOTH strong growth AND
    quality (v1 could hit 10 on growth alone), making the rank more discerning."""
    score = 5.0
    # Growth (primary — Minervini bull)
    pg = _safe_num(row, 'Qtr Profit Var %', 'Qtr Profit Var')
    if pg > 50: score += 1.75
    elif pg > 20: score += 1.0
    sg = _safe_num(row, 'Qtr Sales Var %', 'Qtr Sales Var')
    if sg > 20: score += 0.75
    # Profitability
    roe = _safe_num(row, 'ROE %', 'ROE')
    if roe > 20: score += 0.75
    elif roe > 15: score += 0.4
    roce = _safe_num(row, 'ROCE %', 'ROCE')
    if roce > 20: score += 0.75
    elif roce > 15: score += 0.4
    # Balance sheet (present-guarded — never reward MISSING data)
    de = _safe_num(row, 'Debt to equity', 'Debt / Equity', default=None)
    if de is not None:
        if de < 0.5: score += 0.75
        elif de > 2.0: score -= 0.75
    # Founder backing
    prom = _safe_num(row, 'Promoter holding %', 'Promoter holding')
    if prom > 50: score += 0.5
    elif prom > 40: score += 0.25
    # Income quality
    div = _safe_num(row, 'Div Yld %', 'Div Yld')
    if div > 1.0: score += 0.25
    # Size
    mcap = _safe_num(row, 'Mar Cap Rs.Cr.', 'Mar Cap')
    if 1000 < mcap < 20000: score += 0.25
    
    # Factor in Daily Delivery and Futures OI Change
    score = _adjust_conviction_by_nse_metrics(row, score)
    return round(max(0.0, min(10.0, score)), 1)


def calculate_conviction_score(row):
    """Stage 2 conviction. Uses actual MASTER_scan_results.csv column names.
    NOTE: Quarterly variants used because annual growth cols not in current master.
    To get annual Profit growth / Sales growth, enrich via screener_fetcher.py."""
    if _BULL_CONV_V2:
        return _calc_conviction_v2(row)
    score = 5.0
    # Quarterly profit growth (proxy for annual until enriched)
    pg = _safe_num(row, 'Qtr Profit Var %', 'Qtr Profit Var')
    if pg > 50: score += 2.5
    elif pg > 20: score += 1.5

    # Quarterly sales growth (proxy)
    sg = _safe_num(row, 'Qtr Sales Var %', 'Qtr Sales Var')
    if sg > 20: score += 1.0

    # ROE
    roe = _safe_num(row, 'ROE %', 'ROE')
    if roe > 20: score += 1.0

    # Market cap bias
    mcap = _safe_num(row, 'Mar Cap Rs.Cr.', 'Mar Cap')
    if 1000 < mcap < 20000: score += 0.5
    
    # Factor in Daily Delivery and Futures OI Change
    score = _adjust_conviction_by_nse_metrics(row, score)
    return round(max(0.0, min(10.0, score)), 1)


# ==========================================
# CONVICTION LOGIC — RECOVERY PHASE
# Rewards value, balance sheet strength, and founder backing.
# Does NOT penalise temporarily depressed growth (corrected stocks).
#
# Scoring:
#   +2.0  Debt/Equity < 0.5     (strong balance sheet — survives crises)
#   +1.5  ROE > 15%             (capital efficient, lower bar than normal)
#   +1.0  Promoter Holding > 40%(skin in the game, aligned incentives)
#   +1.0  Dividend Yield > 1%   (institutional quality, real cash generation)
#   +0.5  Large Cap >20,000Cr   (FII favourite, liquidity in risk-off recovery)
#   +0.5  Mid Cap 1,000-20,000  (higher recovery potential vs large cap)
#   -1.0  Debt/Equity > 2.0     (overleveraged — distressed, not discounted)
# ==========================================
def calculate_recovery_conviction_score(row):
    """Recovery-phase conviction. Uses actual MASTER_scan_results.csv column names.

    COLUMNS PRESENT IN CURRENT MASTER FILE:
      'Div Yld %'        → dividend signal (key fixed)
      'ROCE %'           → used as proxy for capital efficiency
      'ROE %'            → present but often NaN in current data
      'Mar Cap Rs.Cr.'   → market cap sizing
      'Qtr Profit Var %' → basic earnings momentum check

    COLUMNS NOT YET IN MASTER FILE (score 0 gracefully, enrich later):
      Debt to equity     → CRITICAL: run screener_fetcher with balance sheet tab
      Promoter holding   → run screener_fetcher with shareholder tab
    """
    # Per-field safe parsing (see _safe_num): one unparseable cell no longer
    # aborts the whole scorer.
    score = 5.0
    # ── Debt/Equity (in dedicated Recovery Screener.in CSVs)
    # Q4 FIX (19 Jun 2026): require D/E to be PRESENT before awarding the
    # "strong balance sheet" bonus. Previously a missing D/E parsed to 0.0 and
    # 0 < 0.5 handed out +2.0 for absent data — rewarding the unknown. Now a
    # missing D/E (None) scores neither the +2.0 bonus nor the -1.0 penalty.
    de = _safe_num(row, 'Debt to equity', 'Debt / Equity', default=None)
    if de is not None:
        if de < 0.5:   score += 2.0
        elif de > 2.0: score -= 1.0

    # ── ROCE as capital efficiency proxy
    roce = _safe_num(row, 'ROCE %', 'ROCE')
    if roce > 20: score += 1.5
    elif roce > 12: score += 0.75

    # ── ROE supplement
    roe = _safe_num(row, 'ROE %', 'ROE')
    if roe > 15: score += 0.5

    # ── Promoter holding
    prom = _safe_num(row, 'Promoter holding %', 'Promoter holding')
    if prom > 40: score += 1.0

    # ── Dividend yield
    div = _safe_num(row, 'Div Yld %', 'Div Yld')
    if div > 1.5: score += 1.0
    elif div > 0.5: score += 0.5

    # ── Quarterly profit growth
    qpg = _safe_num(row, 'Qtr Profit Var %', 'Qtr Profit Var')
    if qpg > 15: score += 0.5

    # ── Market cap sizing
    mcap = _safe_num(row, 'Mar Cap Rs.Cr.', 'Mar Cap')
    if mcap > 20000:          score += 0.5
    elif 1000 < mcap < 20000: score += 0.5
    
    # Factor in Daily Delivery and Futures OI Change
    score = _adjust_conviction_by_nse_metrics(row, score)
    return round(max(0.0, min(10.0, score)), 1)


def _safe_num_val(v, default=0.0):
    if v is None or pd.isna(v):
        return default
    s = str(v).replace(',', '').strip()
    if s.lower() in ('', 'nan', 'n/a', 'na', '-', '--', 'none'):
        return default
    try:
        return float(s)
    except (TypeError, ValueError):
        return default

def _calculate_weighted_overall(df):
    if df is None or df.empty:
        return df
    
    # Ensure target columns exist in df
    for col in ['Overall_Rating', 'Overall_Grade']:
        if col not in df.columns:
            if col == 'Overall_Grade':
                df[col] = None
            else:
                df[col] = float('nan')
            
    for idx, r in df.iterrows():
        cs = _safe_num_val(r.get('Combined_Score'), 0.0)
        conv = _safe_num_val(r.get('Conviction'), 0.0)
        ts = _safe_num_val(r.get('Tech_Score'), 0.0)
        ms = _safe_num_val(r.get('Minervini_Score'), 0.0)
        ps = _safe_num_val(r.get('Piotroski_Score'), 0.0)
        
        # Normalize component scores to 0-100 scale
        cs_norm = cs
        conv_norm = conv * 10.0
        ts_norm = ts
        ms_norm = (ms / 8.0) * 100.0 if ms else 0.0
        ps_norm = (ps / 9.0) * 100.0 if ps else 0.0
        
        # Weighted overall rating
        rating = (0.30 * cs_norm) + (0.15 * conv_norm) + (0.15 * ts_norm) + (0.20 * ms_norm) + (0.20 * ps_norm)
        rating = round(rating, 1)
        
        # Map rating to grade scale
        grade = "A+ EXCEPTIONAL" if rating >= 90 else \
                "A STRONG" if rating >= 80 else \
                "B GOOD" if rating >= 70 else \
                "C FAIR" if rating >= 55 else \
                "D WEAK" if rating >= 40 else "F POOR"
                
        df.at[idx, 'Overall_Rating'] = rating
        df.at[idx, 'Overall_Grade'] = grade
    return df

# ==========================================
# MATCHING LOGIC
# ==========================================
JOIN_DROP_LOG = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                             'logs', 'matcher_join_drops.csv')


def _log_join_drop(name, tech_file, fund_file, df_tech, df_fund, merged):
    """Report what the fundamental inner join discarded, per target.

    The join silently removes technical picks that are absent from the
    Screener.in list. Absent and rejected are NOT the same thing - an absent
    name was never scored - but on the console they looked identical, which is
    how an empty FINAL_EarlyBird_Picks.csv read as "the scan found nothing"
    when the scan had in fact found three names.

    Prints a one-line funnel and appends to logs/matcher_join_drops.csv so the
    drop rate can be read across runs rather than guessed at. Fully guarded:
    logging must never be able to break the matcher.
    """
    try:
        tkeys = [s for s in df_tech['MATCH_KEY'].astype(str) if s and s != 'NAN']
        fkeys = set(df_fund['MATCH_KEY'].astype(str)) if 'MATCH_KEY' in df_fund.columns else set()
        dropped = [s for s in tkeys if s not in fkeys]
        kept = len(tkeys) - len(dropped)
        pct = (len(dropped) / len(tkeys) * 100.0) if tkeys else 0.0

        shown = ' '.join(dropped[:8]) + (' …' if len(dropped) > 8 else '')
        print(f"   🔗 {name}: {len(tkeys)} technical → {kept} matched, "
              f"{len(dropped)} not in {os.path.basename(fund_file)} ({pct:.0f}% dropped)")
        if dropped:
            print(f"      dropped (never scored): {shown}")

        os.makedirs(os.path.dirname(JOIN_DROP_LOG), exist_ok=True)
        new = not os.path.exists(JOIN_DROP_LOG)
        with open(JOIN_DROP_LOG, 'a', encoding='utf-8', newline='') as fh:
            w = csv.writer(fh)
            if new:
                w.writerow(['run_ts', 'target', 'tech_file', 'fund_file',
                            'tech_n', 'fund_n', 'matched_n', 'dropped_n',
                            'dropped_pct', 'dropped_symbols'])
            w.writerow([datetime.now().strftime('%Y-%m-%d %H:%M'), name,
                        os.path.basename(tech_file), os.path.basename(fund_file),
                        len(tkeys), len(fkeys), kept, len(dropped),
                        f"{pct:.1f}", ' '.join(dropped)])
    except Exception as e:
        print(f"   ⚠️  join-drop logging failed for {name}: {e}")


def perform_match(return_raw=False):
    print("=" * 65)
    print("✨ GOLDEN MATCHER PRO — STAGE 2 + RECOVERY PHASE")
    print("=" * 65)

    # Load daily NSE Delivery and F&O Open Interest metrics
    try:
        import nse_archive_fetcher
        print("   📥 Downloading latest daily NSE Delivery and F&O Open Interest metrics...")
        nse_metrics = nse_archive_fetcher.get_nse_metrics()
        print(f"   ✅ Loaded metrics for {len(nse_metrics)} symbols.")
    except Exception as ne:
        print(f"   ⚠️ Could not load daily NSE metrics: {ne}")
        nse_metrics = {}

    if not os.path.exists(MASTER_FILE):
        print(f"❌ CRITICAL: '{MASTER_FILE}' not found.")
        return {} if return_raw else None

    df_fund = pd.read_csv(MASTER_FILE, dtype=str)

    col_fund = next((c for c in df_fund.columns if c.lower() in ['symbol', 'nsecode', 'name']), None)
    if not col_fund:
        print("❌ Error: No Symbol column in Master File.")
        return {} if return_raw else None

    df_fund['MATCH_KEY'] = df_fund[col_fund].astype(str).str.upper().str.strip()

    results_dict = {}

    import datetime
    import glob

    # ── Technical enrichment (P0 ranking fix, 19 Jun 2026) ─────────────────
    # Individual FINAL_*.csv files used to be saved BEFORE enrichment, leaving
    # Stage / Mansfield_RS / Daily_RSI / Daily_ADX / EMA_Stack / Tech_Score /
    # Combined_Score blank — which corrupted every downstream ranking. We now
    # enrich each per-edge watchlist in-place before saving, and reuse the
    # already-enriched frames when building the combined files (no double fetch;
    # OHLCV is parquet-cached via data_provider regardless).
    try:
        import technical_enrichment as _te
        _ENRICH_OK = True
    except Exception as _ee:
        print(f"⚠ technical_enrichment unavailable ({_ee}) — individual watchlists "
              f"will lack Tech_Score/Combined_Score (rankings degraded)")
        _ENRICH_OK = False

    # Tier-1 #1 (20 Jun 2026): fetch the benchmark ONCE and reuse it across all
    # watchlist enrich passes (Hunter/EarlyBird/Leader/Pullback + combined),
    # instead of re-fetching it inside each enrich_dataframe call.
    _bench_close = _te.fetch_benchmark_close() if _ENRICH_OK else None

    def _is_enriched(df) -> bool:
        """True when df already carries populated Combined_Score (avoid re-fetch)."""
        return (df is not None and not df.empty
                and 'Combined_Score' in df.columns
                and df['Combined_Score'].notna().any())

    def _enrich_and_rank(df, label):
        """Add tech + composite scores (if not already present) then sort by
        Combined_Score desc. Safe to call on already-enriched frames."""
        if df is None or df.empty:
            return df
        if not _ENRICH_OK:
            return df
        if not _is_enriched(df):
            n = len(df)
            print(f"   [*] Enriching {n} {label} symbols with technical metrics "
                  f"(Stage/Mansfield/RSI/ADX/...) -- cached after first run.")
            def _prog(i, total, sym):
                if i == 1 or i == total or i % 5 == 0:
                    print(f"      [{i:3d}/{total}] {sym}")
            df = _te.enrich_dataframe(df, progress_cb=_prog, bench_close=_bench_close)
        
        # Calculate/override the weighted Overall_Rating and Overall_Grade using actual matcher columns
        df = _calculate_weighted_overall(df)

        if 'Combined_Score' in df.columns:
            df = df.sort_values('Combined_Score', ascending=False)
        return df

    today_str = datetime.datetime.now().strftime("%d%b%y")

    name_map = {
        "FINAL_Hunter_Picks.csv":           f"Hunters-{today_str}.csv",
        "FINAL_Pullback_Picks.csv":          f"Pullbacks-{today_str}.csv",
        "FINAL_EarlyBird_Picks.csv":         f"EarlyBirds-{today_str}.csv",
        "FINAL_Leader_Picks.csv":            f"Leaders-{today_str}.csv",
        "FINAL_Recovery_RSLeaders.csv":      f"Recovery-RSLeaders-{today_str}.csv",
        "FINAL_Recovery_ClimaxBounce.csv":   f"Recovery-ClimaxBounce-{today_str}.csv",
        "FINAL_Recovery_EarlyBirds.csv":     f"Recovery-EarlyBirds-{today_str}.csv",
    }

    folders = ["Strike", "TV"]
    for folder in folders:
        if not os.path.exists(folder):
            os.makedirs(folder)
        else:
            files = glob.glob(os.path.join(folder, "*.csv"))
            for f in files:
                try: os.remove(f)
                except: pass

    for target in TARGETS:
        tech_file  = target['tech_file']
        out_file   = target['output_file']
        start_name = target['name']
        mode       = target.get('mode', 'stage2')

        export_name = name_map.get(
            out_file,
            out_file.replace("FINAL_", "").replace("_Picks", "") + f"-{today_str}.csv"
        )

        # 10 May 2026 fix: write a header-only stub immediately so the file
        # mtime updates THIS run, even if downstream code `continue`s due to
        # missing/empty input or zero matches. Without this, an empty Chartink
        # scan today left yesterday's FINAL_*.csv on disk untouched, making it
        # impossible to distinguish "ran today, no signals" from "never ran".
        # The actual write at line ~393 (when merge succeeds) overwrites this
        # stub with the full data.
        try:
            save_with_golden_schema(None, out_file)
        except Exception:
            pass

        # ── Load the correct fundamental source ──────────────────────────────
        # Recovery targets use their own dedicated Screener.in CSV
        # (contains Debt/Equity, Promoter Holding, ROCE from recovery screens)
        # Stage 2 targets use the shared MASTER_scan_results.csv
        if mode == 'recovery':
            fund_file = target.get('fund_file', MASTER_FILE)
            if not os.path.exists(fund_file):
                print(f"⏭️  Skipping {start_name} — {fund_file} not found.")
                print(f"   Run screener_fetcher.py + screener_processor.py first.")
                continue
            df_fund_target = pd.read_csv(fund_file, dtype=str)
            col_fund_target = next((c for c in df_fund_target.columns if c.lower() in ['symbol', 'nsecode', 'name']), None)
            if not col_fund_target:
                print(f"❌ No Symbol column in {fund_file}")
                continue
            df_fund_target['MATCH_KEY'] = df_fund_target[col_fund_target].astype(str).str.upper().str.strip()
        else:
            # Stage-2 targets share the master. fund_file MUST be bound here:
            # it is only assigned inside the recovery branch above, so the join-
            # drop logger referencing it raised UnboundLocalError and killed the
            # ENTIRE matcher phase on 14 Aug 2026 - every FINAL_*.csv silently
            # kept the prior run's contents while Phase 5 built watchlists from
            # them. pyflakes cannot see this: the name IS assigned somewhere in
            # the function, just not on every path.
            fund_file = MASTER_FILE
            df_fund_target = df_fund

        if not os.path.exists(tech_file):
            print(f"⏭️  Skipping {start_name} — {tech_file} not found (run scanner first)")
            print(f"   → wrote header-only {out_file} so freshness reflects today")
            continue

        df_tech = pd.read_csv(tech_file, dtype=str)
        if df_tech.empty:
            # 10 May 2026: previously a silent `continue` — the user couldn't tell
            # whether Climax Bounce ran or got swallowed. Now we log clearly.
            print(f"⏭️  Skipping {start_name} — {tech_file} is empty "
                  f"(today's Chartink scan found 0 candidates)")
            print(f"   → wrote header-only {out_file} so freshness reflects today")
            continue

        col_tech = next((c for c in df_tech.columns if c.lower() in ['symbol', 'nsecode']), None)
        if not col_tech:
            print(f"⏭️  Skipping {start_name} — no Symbol/NSECode column in {tech_file}")
            print(f"   → wrote header-only {out_file} so freshness reflects today")
            continue

        df_tech['MATCH_KEY'] = df_tech[col_tech].astype(str).str.upper().str.strip()

        merged = pd.merge(df_fund_target, df_tech, on='MATCH_KEY', how='inner')

        # 13 Aug 2026: the inner join is a SECOND, undeclared gate. A technical
        # pick absent from the fundamental list is never evaluated - which on the
        # console looked identical to one that was evaluated and failed. Measured
        # that day: 131 of 180 picks (73%) were dropped this way, including
        # BOSCHLTD, TITAN, SIEMENS, INDIGO, ICICIBANK, HAL and ABBOTINDIA. That
        # may well be correct behaviour (the master IS four fundamental screens),
        # but it has to be visible to be judged. Log it, do not change the join.
        _log_join_drop(start_name, tech_file, fund_file, df_tech, df_fund_target, merged)

        # CORE UNIVERSE — size / pledge / ownership (13 Aug 2026).
        # The four BULL screens carry mcap > 5000, pledged < 5 and a
        # promoter/institutional floor inside the screener.in query. The three
        # RECOVERY screens carry mcap ONLY - verified live: pledge=False,
        # promoter=False. So a pledged recovery name passed the whole pipeline.
        # Gating here rather than editing Jay's saved screens keeps one definition
        # (core_universe.CONFIG) for all seven targets and for the Catalyst,
        # Pullback and GM surfaces - which is the point of the exercise.
        # None (screener.in unreachable) = do not gate, and say so.
        if not merged.empty:
            try:
                import core_universe as _cu
                _elig = _cu.eligible_symbols()
                if _elig is None:
                    print("   ⚠ CORE gate UNAVAILABLE — size/pledge/ownership NOT applied")
                else:
                    _n0 = len(merged)
                    merged = merged[merged["MATCH_KEY"].map(lambda s: _cu.gate(s, _elig))].copy()
                    if len(merged) != _n0:
                        print(f"   🛡 CORE gate: kept {len(merged)}/{_n0} ({_cu.describe()})")
            except Exception as _cue:
                print(f"   ⚠ CORE gate skipped ({_cue})")

        if merged.empty:
            print(f"⏭️  {start_name}: 0 matches (Chartink had {len(df_tech)} candidates "
                  f"but none matched the Screener.in fundamental list)")
            print(f"   → wrote header-only {out_file} so freshness reflects today")
            continue

        if not merged.empty:
            # Normalise Symbol column
            actual_sym_col = next((c for c in merged.columns if c.lower() == 'symbol'),
                                next((c for c in merged.columns if c.lower() == 'nsecode'),
                                next((c for c in merged.columns if c.lower().endswith('_x')),
                                next((c for c in merged.columns if c.lower().endswith('_y')), None))))
            if actual_sym_col and actual_sym_col != 'Symbol':
                merged.rename(columns={actual_sym_col: 'Symbol'}, inplace=True)
            if 'Symbol' not in merged.columns:
                potential = [c for c in merged.columns if 'sym' in c.lower() or 'code' in c.lower()]
                if potential:
                    merged.rename(columns={potential[0]: 'Symbol'}, inplace=True)
            for col in list(merged.columns):
                if col != 'Symbol' and (col.lower().startswith('symbol_') or col.lower().startswith('nsecode_')):
                    merged.drop(columns=[col], inplace=True)

            # Rename/map column headers from Screener names to Golden schema names
            rename_map = {
                'Return on capital employed': 'ROCE %',
                'Return on equity': 'ROE %',
                'Market Capitalization': 'Mar Cap Rs.Cr.',
                'YOY Quarterly sales growth': 'Qtr Sales Var %',
                'YOY Quarterly profit growth': 'Qtr Profit Var %',
                'Current Price': 'CMP Rs.'
            }
            for src_col, dest_col in rename_map.items():
                actual_col = next((c for c in merged.columns if c.strip().lower() == src_col.lower()), None)
                if actual_col:
                    merged.rename(columns={actual_col: dest_col}, inplace=True)

            # Ensure all fundamental columns exist in merged
            for col in ['ROE %', 'ROE', 'Debt to equity', 'Debt / Equity', 'Promoter holding %', 'Promoter holding',
                        'ROCE %', 'Div Yld %', 'Qtr Profit Var %', 'Qtr Sales Var %', 'Mar Cap Rs.Cr.', 'CMP Rs.', 'P/E',
                        'Minervini_Score', 'Piotroski_Score', 'Overall_Rating', 'Overall_Grade', 'Delivery_Pct', 'Futures_OI_Chg_Pct']:
                if col not in merged.columns:
                    if col == 'Overall_Grade':
                        merged[col] = None
                    else:
                        merged[col] = float('nan')

            # Map daily Delivery and OI change metrics
            for idx, r in merged.iterrows():
                sym = r.get('Symbol')
                if sym:
                    clean_sym = str(sym).replace("NSE:", "").replace("BSE:", "").strip()
                    if clean_sym in nse_metrics:
                        merged.at[idx, 'Delivery_Pct'] = nse_metrics[clean_sym].get('Delivery_Pct')
                        merged.at[idx, 'Futures_OI_Chg_Pct'] = nse_metrics[clean_sym].get('Futures_OI_Chg_Pct')

            # Fetch missing fundamentals from yfinance via fundamental_hub and calculate X-Ray scores
            try:
                import fundamental_hub as _fh
                from weinstein_xray_screener import get_xray_scorecard
                print(f"   📊 Enriching fundamentals & X-Ray Scores for {start_name}...")
                for idx, r in merged.iterrows():
                    sym = r.get('Symbol')
                    if sym:
                        # Clean symbol for yfinance (append .NS if needed)
                        yf_sym = str(sym).replace("NSE:", "").replace("BSE:", "").strip()
                        if not yf_sym.endswith(".NS") and not yf_sym.endswith(".BO") and not yf_sym.startswith("^"):
                            yf_sym = f"{yf_sym}.NS"
                        
                        # Calculate X-Ray scorecard
                        try:
                            sc = get_xray_scorecard(yf_sym)
                            if sc and "error" not in sc:
                                merged.at[idx, 'Minervini_Score'] = sc.get('Minervini_Score', 0)
                                merged.at[idx, 'Piotroski_Score'] = sc.get('Piotroski_Score', 0)
                                merged.at[idx, 'Overall_Rating'] = sc.get('Overall_Rating', 0)
                                merged.at[idx, 'Overall_Grade'] = sc.get('Overall_Grade', 'N/A')
                            else:
                                merged.at[idx, 'Minervini_Score'] = float('nan')
                                merged.at[idx, 'Piotroski_Score'] = float('nan')
                                merged.at[idx, 'Overall_Rating'] = float('nan')
                                merged.at[idx, 'Overall_Grade'] = 'N/A'
                        except Exception as _xre:
                            print(f"   ⚠️ X-Ray Scorecard failed for {yf_sym}: {_xre}")
                            merged.at[idx, 'Minervini_Score'] = float('nan')
                            merged.at[idx, 'Piotroski_Score'] = float('nan')
                            merged.at[idx, 'Overall_Rating'] = float('nan')
                            merged.at[idx, 'Overall_Grade'] = 'N/A'
                        
                        # Check which columns are missing or NaN
                        roe_val = r.get('ROE %')
                        need_roe = pd.isna(roe_val) or roe_val == "" or str(roe_val).lower() == "nan"
                        
                        roce_val = r.get('ROCE %')
                        need_roce = pd.isna(roce_val) or roce_val == "" or str(roce_val).lower() == "nan"
                        
                        de_val = r.get('Debt to equity')
                        need_de = pd.isna(de_val) or de_val == "" or str(de_val).lower() == "nan"
                        
                        prom_val = r.get('Promoter holding %')
                        need_prom = pd.isna(prom_val) or prom_val == "" or str(prom_val).lower() == "nan"
                        
                        div_val = r.get('Div Yld %')
                        need_div = pd.isna(div_val) or div_val == "" or str(div_val).lower() == "nan"
                        
                        pe_val = r.get('P/E')
                        need_pe = pd.isna(pe_val) or pe_val == "" or str(pe_val).lower() == "nan"
                        
                        mcap_val = r.get('Mar Cap Rs.Cr.')
                        need_mcap = pd.isna(mcap_val) or mcap_val == "" or str(mcap_val).lower() == "nan"
                        
                        cmp_val = r.get('CMP Rs.')
                        need_cmp = pd.isna(cmp_val) or cmp_val == "" or str(cmp_val).lower() == "nan"
                        
                        qpg_val = r.get('Qtr Profit Var %')
                        need_qpg = pd.isna(qpg_val) or qpg_val == "" or str(qpg_val).lower() == "nan"
                        
                        qsg_val = r.get('Qtr Sales Var %')
                        need_qsg = pd.isna(qsg_val) or qsg_val == "" or str(qsg_val).lower() == "nan"
                        
                        if (need_roe or need_roce or need_de or need_prom or need_div or need_pe or need_mcap or need_cmp or need_qpg or need_qsg):
                            fund_data = _fh.fetch_stock_fundamentals(yf_sym)
                            if fund_data:
                                if need_roe and 'roe' in fund_data and fund_data['roe'] is not None:
                                    merged.at[idx, 'ROE %'] = round(float(fund_data['roe']), 2)
                                    merged.at[idx, 'ROE'] = round(float(fund_data['roe']), 2)
                                if need_roce and 'roce' in fund_data and fund_data['roce'] is not None:
                                    merged.at[idx, 'ROCE %'] = round(float(fund_data['roce']), 2)
                                if need_de and 'debt_equity' in fund_data and fund_data['debt_equity'] is not None:
                                    merged.at[idx, 'Debt to equity'] = round(float(fund_data['debt_equity']), 2)
                                    merged.at[idx, 'Debt / Equity'] = round(float(fund_data['debt_equity']), 2)
                                if need_prom and 'promoter_holding' in fund_data and fund_data['promoter_holding'] is not None:
                                    merged.at[idx, 'Promoter holding %'] = round(float(fund_data['promoter_holding']), 2)
                                    merged.at[idx, 'Promoter holding'] = round(float(fund_data['promoter_holding']), 2)
                                if need_div and 'dividend_yield' in fund_data and fund_data['dividend_yield'] is not None:
                                    merged.at[idx, 'Div Yld %'] = round(float(fund_data['dividend_yield']), 2)
                                if need_pe and 'pe_ratio' in fund_data and fund_data['pe_ratio'] is not None:
                                    merged.at[idx, 'P/E'] = round(float(fund_data['pe_ratio']), 2)
                                if need_mcap and 'market_cap' in fund_data and fund_data['market_cap'] is not None:
                                    merged.at[idx, 'Mar Cap Rs.Cr.'] = round(float(fund_data['market_cap']), 2)
                                if need_cmp and 'price' in fund_data and fund_data['price'] is not None:
                                    merged.at[idx, 'CMP Rs.'] = round(float(fund_data['price']), 2)
                                if need_qpg and 'earnings_growth' in fund_data and fund_data['earnings_growth'] is not None:
                                    merged.at[idx, 'Qtr Profit Var %'] = round(float(fund_data['earnings_growth']), 2)
                                if need_qsg and 'revenue_growth' in fund_data and fund_data['revenue_growth'] is not None:
                                    merged.at[idx, 'Qtr Sales Var %'] = round(float(fund_data['revenue_growth']), 2)
            except Exception as _fe:
                print(f"   ⚠️ Fundamentals enrichment failed: {_fe}")

            # ── CONVICTION SCORING ──────────────────────────────────────────
            if mode == 'recovery':
                print(f"\n🔄 [{start_name}] — RECOVERY conviction scorer (balance sheet + value)")
                merged['Conviction'] = merged.apply(calculate_recovery_conviction_score, axis=1)
            else:
                merged['Conviction'] = merged.apply(calculate_conviction_score, axis=1)

            merged = merged.sort_values(by='Conviction', ascending=False)

            # ── AI CATALYST (STRICT PINE-SYNCED) ────────────────────────────
            import bull_screener
            catalysts = []
            print(f"   ⚙️  Strict Catalyst Analysis for {start_name} Top Picks (Pine-Synced)...")
            
            global _df_bench_cache
            if '_df_bench_cache' not in globals() or _df_bench_cache is None:
                try:
                    import data_provider as _dp
                    _df_bench_cache = bull_screener._flatten_cols(_dp.fetch_ohlcv(bull_screener.BENCHMARK_YF, period="3y", interval="1wk", use_cache=True, auto_adjust=True))
                except Exception:
                    _df_bench_cache = None
            
            for i, r in merged.iterrows():
                sym_val = r.get('Symbol', r.get('NSECode', 'Unknown'))
                try:
                    res = bull_screener.screen_symbol(sym_val, _df_bench_cache, force_output=False, mkt_bull=True)
                    cat = res.get('Catalyst', 'NONE') if res else 'NONE'
                except Exception as e:
                    cat = 'NONE'
                catalysts.append(cat)
            merged['Hybrid_Catalyst'] = catalysts

            # ── WEEKLY STAGE GATE ───────────────────────────────────────────
            # Stage 2:  strict  — must be ABOVE 30W SMA
            # Recovery: relaxed — allows up to 10% BELOW 30W SMA (basing stocks)
            print(f"   🛡️  Weekly Stage Gate [{mode.upper()}] for {start_name}...")
            weekly_pass = []
            try:
                # A8 + C1: was a per-symbol yfinance loop with 0.3s sleep — for
                # 100 stocks that's 30s of pure delay plus N network round-trips.
                # Now: one batched download via data_provider (parquet-cached),
                # 50 symbols per call to stay under yfinance batch limits.
                try:
                    import data_provider as _dp
                    _USE_DP = True
                except Exception:
                    _dp = None
                    _USE_DP = False
                import yfinance as yf

                # Build the symbol order we need to score against `merged`
                ordered_syms = []
                for _, row in merged.iterrows():
                    sym = str(row.get('Symbol', '')).replace("NSE:", "").replace("BSE:", "").strip()
                    ordered_syms.append(sym)

                # Batch fetch all weekly data in groups of 50
                wmap = {}  # symbol -> weekly DataFrame
                BATCH = 50
                unique_syms = [s for s in dict.fromkeys(ordered_syms) if s]
                for i in range(0, len(unique_syms), BATCH):
                    chunk = unique_syms[i:i + BATCH]
                    import data_provider as _dp
                    try:
                        wmap.update(_dp.fetch_batch_ohlcv(chunk, period="1y", interval="1wk", use_cache=True, auto_adjust=True))
                    except Exception as _be:
                        print(f"   ⚠️ Stage-gate batch failed: {_be}")

                # Score each row against the cached/batched data
                for sym in ordered_syms:
                    if not sym:
                        weekly_pass.append("N/A")
                        continue
                    wdata = wmap.get(sym)
                    if wdata is None or wdata.empty or len(wdata) < 30:
                        weekly_pass.append("UNKNOWN")
                        continue
                    try:
                        weekly_close = float(wdata['Close'].iloc[-1])
                        weekly_sma30 = float(wdata['Close'].rolling(30).mean().iloc[-1])
                        floor = weekly_sma30 * 0.90 if mode == 'recovery' else weekly_sma30
                        weekly_pass.append("PASS" if weekly_close >= floor else "FAIL")
                    except Exception as _se:
                        print(f"   ⚠️ Stage-gate score failed for {sym}: {_se}")
                        weekly_pass.append("UNKNOWN")

                merged['Weekly_Stage_Gate'] = weekly_pass
                rejected = merged[merged['Weekly_Stage_Gate'] == 'FAIL']
                if not rejected.empty:
                    rej_syms = rejected.get('Symbol', pd.Series()).tolist()
                    print(f"   ⛔ Stage Gate REJECTED {len(rejected)}: {', '.join(str(s) for s in rej_syms[:5])}")
                # A9: also surface UNKNOWN count so user sees yfinance-throttle impact
                unknown = merged[merged['Weekly_Stage_Gate'] == 'UNKNOWN']
                if not unknown.empty:
                    print(f"   ⚠️  Stage Gate UNKNOWN {len(unknown)} (yfinance unavailable — kept, review manually)")
                # Drop only confirmed-failed rows; keep PASS and UNKNOWN
                merged = merged[merged['Weekly_Stage_Gate'] != 'FAIL'].drop(columns=['Weekly_Stage_Gate'])
            except Exception as e:
                print(f"   ⚠️ Weekly Gate Error: {e} (proceeding without filter)")

        if 'MATCH_KEY' in merged.columns:
            merged.drop(columns=['MATCH_KEY'], inplace=True)

        if "Symbol" not in merged.columns:
            print(f"   ℹ️  No matches found for {start_name}.")
            save_with_golden_schema(None, out_file)
            results_dict[start_name] = (mode, pd.DataFrame(columns=['Symbol']))
            continue

        # ── P0 fix: enrich BEFORE saving so the individual per-edge watchlist
        # carries Stage/Mansfield/RSI/ADX/Tech_Score/Combined_Score and is
        # ranked. The enriched frame is reused for the combined files below.
        merged = _enrich_and_rank(merged, start_name)

        # Save full data
        save_with_golden_schema(merged, out_file)
        print(f"✅ {start_name}: Saved → {out_file} (ranked by Combined_Score)")

        if not merged.empty:
            results_dict[start_name] = (mode, merged)

    # ── COMBINED OUTPUT (split by mode) ─────────────────────────────────────
    bull_dfs     = []
    recovery_dfs = []
    for name, (entry_mode, df) in results_dict.items():
        if entry_mode == 'recovery':
            recovery_dfs.append(df)
        else:
            bull_dfs.append(df)

    # Technical enrichment (_te / _ENRICH_OK / _enrich_and_rank) was set up at
    # the top of perform_match. The per-edge frames in results_dict are ALREADY
    # enriched + ranked, so _enrich_and_rank below just concatenates and re-sorts
    # (it skips re-fetching when Combined_Score is already populated).
    def _save_combined(dfs, csv_name, txt_name, label):
        if not dfs:
            save_with_golden_schema(None, csv_name)
            with open(txt_name, "w") as f:
                f.write("")
            return None
        combined = pd.concat(dfs, ignore_index=True)
        if 'Symbol' not in combined.columns:
            save_with_golden_schema(None, csv_name)
            with open(txt_name, "w") as f:
                f.write("")
            return None
        combined = combined.drop_duplicates(subset=['Symbol'])
        # ── Enrich with technicals + composite ranking ────────────────────
        combined = _enrich_and_rank(combined, label)
        save_with_golden_schema(combined, csv_name)
        print(f"\n🌟 {label} Combined Picks (Unique: {len(combined)}) → {csv_name}")
        sym_list = combined['Symbol'].apply(
            lambda x: x if "NSE:" in str(x) or "BSE:" in str(x) else f"NSE:{x}"
        ).tolist()
        with open(txt_name, "w") as f:
            f.write(",".join(sym_list))
        print(f"   📂 Pine Script paste-ready → {txt_name}")
        return combined

    bull_combined_enriched     = _save_combined(bull_dfs,     "FINAL_COMBINED_BULL_PICKS.csv",     "FINAL_COMBINED_BULL_SYMBOLS.txt",     "Bull Market")
    recovery_combined_enriched = _save_combined(recovery_dfs, "FINAL_COMBINED_RECOVERY_PICKS.csv", "FINAL_COMBINED_RECOVERY_SYMBOLS.txt", "Recovery")

    # ── ALL-COMBINED + GOLDEN WATCHLIST (10 May 2026 fix) ─────────────────────
    # Two files documented in Bible §6E + the WATCHLIST Pipeline Health panel
    # but previously not generated by this matcher (legacy stubs from Jan/Apr).
    #
    #   FINAL_COMBINED_PICKS.csv  → everything (Bull + Recovery) deduped,
    #                               ranked by Conviction desc. Full columns.
    #   FINAL_WATCHLIST.csv       → "Golden Watchlist" — top 25 by Conviction
    #                               with focused columns. The single best file
    #                               to load into TradingView per Bible §6E.
    # ── ALL-COMBINED + GOLDEN WATCHLIST — use the already-enriched dfs ─────
    # so we don't re-fetch the same symbols twice. Bull-combined and
    # Recovery-combined have already been enriched + ranked by _save_combined.
    parts = []
    if bull_combined_enriched is not None and not bull_combined_enriched.empty:
        parts.append(bull_combined_enriched)
    if recovery_combined_enriched is not None and not recovery_combined_enriched.empty:
        parts.append(recovery_combined_enriched)

    if parts:
        all_combined = pd.concat(parts, ignore_index=True)
        if 'Symbol' in all_combined.columns:
            all_combined = all_combined.drop_duplicates(subset=['Symbol'])
            # Rank by Combined_Score if enrichment ran, else by Conviction
            sort_col = 'Combined_Score' if 'Combined_Score' in all_combined.columns \
                       else 'Conviction'
            if sort_col in all_combined.columns:
                all_combined['_Sort_Num'] = pd.to_numeric(
                    all_combined[sort_col], errors='coerce'
                ).fillna(0)
                all_combined = (all_combined
                                .sort_values('_Sort_Num', ascending=False)
                                .drop(columns=['_Sort_Num']))

            # FINAL_COMBINED_PICKS.csv — full columns (now with technicals)
            if save_with_golden_schema(all_combined, "FINAL_COMBINED_PICKS.csv"):
                print(f"\n🌟 ALL Combined Picks (Unique: {len(all_combined)}) → FINAL_COMBINED_PICKS.csv")
                print(f"   Ranked by {sort_col} (Conviction 50% + Tech 50%)")

            # Companion symbol list for Pine paste
            sym_list = all_combined['Symbol'].apply(
                lambda x: x if "NSE:" in str(x) or "BSE:" in str(x) else f"NSE:{x}"
            ).tolist()
            with open("FINAL_COMBINED_SYMBOLS.txt", "w") as f:
                f.write(",".join(sym_list))
            print(f"   📂 Pine Script paste-ready → FINAL_COMBINED_SYMBOLS.txt")

            # FINAL_WATCHLIST.csv — Golden Watchlist (top 25, full 26 cols format)
            # Now includes the new tech metrics + composite scores upfront, enforcing the 26 golden columns schema.
            golden = all_combined.head(25).copy()
            if save_with_golden_schema(golden, "FINAL_WATCHLIST.csv"):
                print(f"\n🏆 Golden Watchlist (top {len(golden)} by {sort_col}) → FINAL_WATCHLIST.csv")
                print(f"   Per Bible §6E — single best file to load into TradingView for Phase 3 validation")
    else:
        save_with_golden_schema(None, "FINAL_COMBINED_PICKS.csv")
        save_with_golden_schema(None, "FINAL_WATCHLIST.csv")
        with open("FINAL_COMBINED_SYMBOLS.txt", "w") as f:
            f.write("")
        print(f"\n🌟 ALL Combined Picks: 0 matches found.")

    print("\n🏁 Matching Complete.")

    if return_raw:
        return results_dict


if __name__ == "__main__":
    perform_match()
    input("\nPress Enter to exit...")