import sys
if sys.stdout.encoding.lower() != 'utf-8':
    sys.stdout.reconfigure(encoding='utf-8')

import asyncio
from playwright.async_api import async_playwright
import os
import time
import re

# ==========================================
# CONFIGURATION
# ==========================================
WATCHLIST_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "Generated_Watchlists")
TV_URL = "https://in.tradingview.com/chart/"
# Versioning to v2 to bypass existing profile corruption
USER_DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "tv_user_data_v2")

import datetime


def _is_file_from_today(path):
    """True if `path` was last modified today — rejects STALE LATEST_ watchlist
    files so a prior run's picks are never uploaded as if fresh. Parity with
    strike_automation.py's stale-guard."""
    try:
        return datetime.datetime.fromtimestamp(os.path.getmtime(path)).date() == datetime.datetime.now().date()
    except Exception:
        return False

# Files to Import
# We use base names. The script will append DATE suffix (e.g., Hunter-10FEB26.txt)
TARGET_BASES = [
    "Bull_EarlyBird",
    "Bull_Hunter",
    "Bull_Pullback",
    "Bull_StrongLeader",
    "Bull_Picks_All",
    "Rec_Climax_Bounce",
    "Rec_Early_Bird",
    "Rec_RS_Survivor",
    "Recovery_Picks_All",
    # Catalyst watchlists: bull broad catalyst-first scan (FINAL_CATALYST_
    # WATCHLIST.csv, Phase 4.7, RFF-gated) + recovery catalyst companion
    # (FINAL_RECOVERY_CATALYST_WATCHLIST.csv, Phase 4.75 — FIRING REV/WYC only).
    # Generated by watchlist_manager. Replaced the raw "Rec_Screener" log
    # (6 Jul 2026): it pushed ~76 non-firing candidates; the companion carries
    # only the ~16 validated firing signals.
    "Catalyst_Watchlist",
    "Recovery_Catalyst_Watchlist",
    "Golden_Matcher_Picks",
    # Consolidated Trigger-Board union (run_pipeline Phase 4.8) — the single list
    # of every name the Golden Matcher Trigger Board evaluates.
    "Golden_Matcher_Board",
    "XRay_Picks",
    "Portfolio"
]

def cleanup_singleton_lock():
    """Nuclear Cleanup: Removes all stale locks, ports, and SQLite journal files that trigger TargetClosedError."""
    print("🧹 Starting Nuclear Profile Cleanup...")
    
    # 1. Direct targets (Root level)
    root_locks = ["SingletonLock", "SingletonCookie", "SingletonSocket", "DevToolsActivePort"]
    for lock in root_locks:
        path = os.path.join(USER_DATA_DIR, lock)
        if os.path.exists(path):
            try:
                os.remove(path)
                print(f"   🗑️ Root Lock Removed: {lock}")
            except: pass

    # 2. Recursive cleanup for Journals and WALs (Common crash culprits in Chromium)
    # We look for files ending in -journal, -wal, -shm, or named LOCK
    crash_patterns = ["-journal", "-wal", "-shm", "LOCK"]
    cleaned_count = 0
    
    try:
        for root, dirs, files in os.walk(USER_DATA_DIR):
            for file in files:
                if any(file.endswith(p) or file == p for p in crash_patterns):
                    file_path = os.path.join(root, file)
                    try:
                        os.remove(file_path)
                        cleaned_count += 1
                    except:
                        pass
        if cleaned_count > 0:
            print(f"   🧼 Deep Clean: Removed {cleaned_count} stagnant artifact files.")
    except Exception as e:
        print(f"   ⚠️ Recursive cleanup notice: {e}")

async def run_sync(pipeline_mode=False):
    print("🚀 STARTING TRADINGVIEW WATCHLIST SYNC...")
    
    # Clear any stale automated Chrome processes before starting
    try:
        from kill_chrome import kill_automation_chrome
        kill_automation_chrome()
    except Exception as ce:
        print(f"⚠️ Warning: Pre-run Chrome cleanup returned: {ce}")

    if not os.path.exists(WATCHLIST_DIR):
        print(f"❌ Error: Watchlist directory not found: {WATCHLIST_DIR}")
        return

    # 0. Clean up locks before starting
    cleanup_singleton_lock()

    max_retries = 3
    for attempt in range(max_retries):
        try:
            async with async_playwright() as p:
                # Launch with persistent context to keep login
                print(f"📂 User Data Dir: {USER_DATA_DIR} (Attempt {attempt+1}/{max_retries})")
                
                # Use absolute paths and ensure they are normalized for Windows
                clean_user_dir = os.path.normpath(os.path.abspath(USER_DATA_DIR))
                
                context = None
                try:
                    context = await p.chromium.launch_persistent_context(
                        user_data_dir=clean_user_dir,
                        headless=False,
                        channel="chrome", # Switching to real Chrome for better auth/persistence
                        args=[
                            "--start-maximized",
                            "--disable-blink-features=AutomationControlled",
                            # Removed --no-sandbox as it can sometimes trigger Guest mode on Windows
                            "--disable-dev-shm-usage",
                            "--disable-gpu", 
                            "--disable-software-rasterizer",
                        ],
                        user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
                        no_viewport=True,
                        timeout=60000 
                    )
                    
                    # Verify we aren't in a guest/temporary state
                    print(f"✅ Browser session active (Profile: {os.path.basename(clean_user_dir)})")
                    print("⚠️  PLEASE LOG IN TO TRADINGVIEW NOW IF NOT ALREADY LOGGED IN.")
                    print("⚠️  This is a one-time login for the new stable profile (v2).")
                    
                    # If we got here, launch succeeded
                    await process_sync(context)
                    return # Exit successfully
                finally:
                    if context:
                        print("🔒 Closing persistent browser context...")
                        await context.close()

        except Exception as e:
            print(f"⚠️ Launch attempt {attempt+1} failed: {e}")
            if attempt < max_retries - 1:
                print("🔄 Retrying in 3 seconds...")
                await asyncio.sleep(3)
                cleanup_singleton_lock() # Try cleaning locks again
            else:
                print("❌ All launch attempts failed. Please ensure no hidden Chrome processes are running.")
                raise e

async def dismiss_modals(page):
    """Aggressively closes any TradingView popups or modals that block the UI."""
    modal_selectors = [
        "button[data-name='close']",
        ".tv-dialog__close",
        "[data-role='modal-container'] button:has-text('Close')",
        "button[aria-label='Close']",
        ".js-dialog__close"
    ]
    for selector in modal_selectors:
        try:
            close_btn = page.locator(selector).first
            if await close_btn.is_visible():
                print(f"      🧹 Closing modal using: {selector}")
                await close_btn.click()
                await page.wait_for_timeout(500)
        except:
            pass

async def cleanup_old_watchlists(page, base_name):
    """Deletes stale watchlists created by Auto-pilot for a specific base_name."""
    print(f"   🧹 Checking for stale '{base_name}' watchlists...")
    date_suffix = datetime.datetime.now().strftime("%d%b%y").upper()
    current_today_upper = f"{base_name}-{date_suffix}".upper()
    # Relaxed pattern to find the base name followed by a date anywhere in the string
    pattern = re.compile(rf"{re.escape(base_name)}-\d{{2}}[A-Z]{{3}}\d{{2}}", re.IGNORECASE)
    
    try:
        menu_trigger = page.locator("button[data-name='watchlists-button']").first
        if not await menu_trigger.is_visible():
            print("      ⚠️ Watchlists button not visible, skipping cleanup.")
            return

        await menu_trigger.click()
        await page.wait_for_timeout(1000)
        
        # In TV, dropdown items are often in a popup overlay
        menu_items = page.locator("div[data-role='menuitem'], div[role='option'], .item-text")
        count = await menu_items.count()
        to_delete = []
        
        for i in range(count):
            try:
                item_text = await menu_items.nth(i).inner_text()
                # Normalize spaces and newlines
                item_text = re.sub(r'\s+', ' ', item_text).strip()
                # We ALWAYS add it to 'to_delete' (even if it's from today) so we don't end up 
                # with duplicate watchlists when running the script multiple times a day.
                if pattern.search(item_text):
                    to_delete.append(item_text)
                elif f"{base_name} [Auto]".upper() in item_text.upper():
                    to_delete.append(item_text)
            except:
                pass

        # Close the dropdown before proceeding
        await page.keyboard.press("Escape")
        await page.wait_for_timeout(500)

        for wl_name in to_delete:
            print(f"   🗑️ Deleting stale watchlist: {wl_name}")
            try:
                await menu_trigger.click()
                await page.wait_for_timeout(1000)
                
                # Robustly find the watchlist item with Regex for exact matching (avoids false substrings)
                wl_item = page.locator("div[data-role='menuitem'], div[role='option'], .item-text, span.label-hlEa5N5c").filter(
                    has_text=re.compile(rf"^\s*{re.escape(wl_name)}\s*$", re.IGNORECASE)
                ).first
                if await wl_item.is_visible():
                    await wl_item.click()
                    await page.wait_for_timeout(2000) # Wait for it to load
                    
                    # Click Advanced menu (3 dots)
                    adv_menu = page.locator("button[data-name='advanced-menu'], button[aria-label='More']").first
                    if await adv_menu.is_visible():
                        await adv_menu.click()
                        await page.wait_for_timeout(1000)
                        
                        delete_opt = page.locator("text='Delete list', text='Delete'").first
                        if await delete_opt.is_visible():
                            await delete_opt.click()
                            await page.wait_for_timeout(1000)
                            
                            confirm_btn = page.locator("button[data-name='submit-button'], button:has-text('Yes'), button:has-text('Delete')").first
                            if await confirm_btn.is_visible():
                                await confirm_btn.click()
                                print(f"      ✅ Deleted {wl_name}")
                                await page.wait_for_timeout(1500)
                        else:
                            print(f"      ⚠️ 'Delete list' option not found in advanced menu.")
                            await page.keyboard.press("Escape")
                    else:
                        print(f"      ⚠️ Advanced menu '...' not found.")
                else:
                    await page.keyboard.press("Escape")
            except Exception as e:
                print(f"      ⚠️ Failed to delete {wl_name}: {e}")
                await page.keyboard.press("Escape")
                
    except Exception as e:
        print(f"   ⚠️ Error during cleanup: {e}")
        await page.keyboard.press("Escape")

async def wait_for_login(page, context):
    """Pauses and waits for the user to log in manually. Injects Proceed/Reset buttons for override."""
    print("🕵️  Detecting Login Status...")
    start_time = time.time()
    max_wait = 360 # Increased to 6 mins
    
    while (time.time() - start_time) < max_wait:
        # 0. RE-INJECT SAFETY RESET (If missing)
        try:
            await page.evaluate("""() => {
                if (document.getElementById('ai-control-panel')) return;
                
                const container = document.createElement('div');
                container.id = 'ai-control-panel';
                container.style = 'position: fixed; top: 10px; right: 10px; z-index: 999999;';
                
                const resetBtn = document.createElement('button');
                resetBtn.id = 'ai-reset-btn';
                resetBtn.innerHTML = 'RESET AUTH (Emergency)';
                resetBtn.style = 'padding: 8px 12px; background: rgba(244,67,54,0.3); color: white; border: 1px solid white; border-radius: 4px; cursor: pointer; font-size: 10px; font-weight: bold; font-family: sans-serif; opacity: 0.6;';
                resetBtn.onmouseover = () => { resetBtn.style.opacity = '1.0'; resetBtn.style.background = '#f44336'; };
                resetBtn.onmouseout = () => { resetBtn.style.opacity = '0.6'; resetBtn.style.background = 'rgba(244,67,54,0.3)'; };
                resetBtn.onclick = () => { 
                    resetBtn.innerHTML = '🔄 RESETTING...'; 
                    window.location.href = 'https://in.tradingview.com/logout/';
                    resetBtn.dataset.clicked = 'true'; 
                };
                
                container.appendChild(resetBtn);
                document.body.appendChild(container);
            }""")
        except:
            pass

        # 0.5 DIAGNOSTIC: Print URL and Title
        try:
            url = page.url
            title = await page.title()
            print(f"      [DEBUG] Current URL: {url[:60]}... | Title: {title[:30]}")
        except:
            pass

        # 1. Reset Override (User clicked the red button)
        reset_click = page.locator("#ai-reset-btn[data-clicked='true']").first
        if await reset_click.count() > 0:
            print("🔄 Reset Requested. Clearing cookies and redirecting...")
            await context.clear_cookies()
            await page.evaluate("localStorage.clear(); sessionStorage.clear();")
            await page.goto("https://www.tradingview.com/chart/")
            await page.evaluate("document.getElementById('ai-reset-btn').dataset.clicked = 'false'; document.getElementById('ai-reset-btn').innerHTML = 'RESET AUTH (Emergency)';")
            continue

        # 2. Automatic Login Detection (User Profile Icon or Chart Layout)
        # Check for core layout areas that only fully load on the chart view when authenticated
        user_menu = page.locator("button[data-name='user-menu'], button[data-name='header-toolbar-user-menu'], .layout__area--right, .layout__area--left, div[class*='chart-gui-wrapper'], div[data-name='legend']").first
        if await user_menu.is_visible():
            print("✅ Login Detected (Workspace/User Menu Visible)! Proceeding automatically...")
            await page.evaluate("document.getElementById('ai-control-panel')?.remove()")
            await dismiss_modals(page)
            return True
        
        # 4. Check for Sign-in indicators
        sign_in = page.locator("button:has-text('Sign in'), .header-signin-button").first
        if await sign_in.is_visible():
             print("⏳ Sign-in button detected. Please log in to your Premium account.")
        else:
             # Check for common "Basic Plan" or "Sign in" modals (like the one in user screenshot)
             modal_check = page.locator("text='Sort your symbols better', text='30-day free trial'").first
             if await modal_check.count() > 0:
                  print("⚠️  Upgrade/Login modal detected. Clearing...")
                  await dismiss_modals(page)
             else:
                  print("⏳ Waiting for login... or use the red 'RESET' button to re-auth.")
                
        await asyncio.sleep(4)
    
    print("❌ Login detection timed out after 6 minutes.")
    return False

async def process_sync(context):
    """The main logic of the sync process after browser launch."""
    try:
        page = context.pages[0] if context.pages else await context.new_page()
        
        print("🌍 Navigating to TradingView Chart...")
        await page.goto(TV_URL)
        
        # 1. AUTH SAFEGUARD: Wait for user to log in
        authenticated = await wait_for_login(page, context)
        if not authenticated:
            print("❌ Authentication failed or timed out. Exiting sync.")
            return

        # Wait for load - adjust selector if needed (e.g., legend or chart canvas)
        try:
            await page.wait_for_selector(".layout__area--right", timeout=15000)
            print("✅ Chart Loaded.")
        except:
            print("⚠️ Timeout waiting for chart (might still be ok)...")

        # Give a moment for dynamic widgets
        await page.wait_for_timeout(3000)

        # Ensure Watchlist Widget is Open
        print("👀 Checking if Watchlist Panel is open...")
        try:
            # Check if the watchlist widget is visible
            # The widgetbar pages wrapper width is a good indicator
            pages_wrap = page.locator("div[data-name='widgetbar-pages-with-tabs']")
            
            is_open = False
            if await pages_wrap.count() > 0:
                box = await pages_wrap.bounding_box()
                if box and box['width'] > 10:
                    is_open = True
            
            if not is_open:
                print("   👉 Panel seems closed. Opening Watchlist Panel...")
                # Click the toggle button in the toolbar
                # Found via debug snippet: data-name="base"
                toggle_btn = page.locator("button[data-name='base']").first
                if await toggle_btn.count() > 0:
                     await toggle_btn.click()
                     await page.wait_for_timeout(1500)
                else:
                     print("   ⚠️ specific 'base' toggle button not found, scanning toolbar...")
                     await page.locator("button[data-tooltip='Watchlist, details and news']").click()
                     await page.wait_for_timeout(1500)
            else:
                print("   ✅ Watchlist Panel is already open.")
                
        except Exception as e:
            print(f"   ⚠️ Error checking watchlist panel: {e}")

        # Generate Date Suffix to match watchlist_manager.py
        # e.g., 09FEB26
        date_suffix = datetime.datetime.now().strftime("%d%b%y").upper()
        
        for base_name in TARGET_BASES:
            # --- DELETION IS NOW HERE TO ALWAYS PURGE STALE LISTS, EVEN IF NO NEW PICKS ---
            await cleanup_old_watchlists(page, base_name)
            
            # Construct filename: Hunter-09FEB26.txt
            filename = f"{base_name}-{date_suffix}.txt"
            file_path = os.path.join(WATCHLIST_DIR, filename)

            # Prefer today's DATED file. If it's missing, fall back to LATEST_
            # ONLY when it was written TODAY — never upload a prior run's stale
            # list under today's date (parity with strike_automation.py). Dated
            # files are fresh by construction: watchlist_manager writes the dated
            # + LATEST_ pair together, and only when today's scan had picks. The
            # cleanup_old_watchlists() call above already purged any old list.
            if not os.path.exists(file_path):
                fallback = os.path.join(WATCHLIST_DIR, f"LATEST_{base_name}.txt")
                if os.path.exists(fallback) and _is_file_from_today(fallback):
                    print(f"⚠️ Dated file missing ({filename}); using FRESH LATEST fallback.")
                    file_path = fallback
                elif os.path.exists(fallback):
                    _age = (datetime.datetime.now() - datetime.datetime.fromtimestamp(os.path.getmtime(fallback))).days
                    print(f"⚠️ LATEST_{base_name}.txt is STALE ({_age}d old) — today's scan "
                          f"produced no picks. Skipping (won't upload prior-run symbols).")
                    continue
                else:
                    print(f"⚠️ Skipping missing file: {filename} (no dated or LATEST_ file).")
                    continue

            if os.path.getsize(file_path) == 0:
                print(f"⚠️ Skipping empty file: {filename}")
                continue
                
            print(f"📂 Processing: {filename}")
            
            try:
                # --- UPLOAD SECTION ---
                print("   Clicking Menu Trigger (Watchlist Switcher)...")
                # Wait for menu to be closed or open?
                # We need to click "Import list". 
                # If we just deleted, the menu might be closed or open depending on the deletion flow.
                # Let's just standardly open it.
                
                menu_trigger = page.locator("button[data-name='watchlists-button']").first
                     
                # Ensure menu is open before clicking "Upload list"
                upload_item = page.locator("div[data-role='menuitem']").filter(has_text="Upload list").first
                if not await upload_item.is_visible():
                     print("      📂 Menu closed. Opening...")
                     await menu_trigger.click()
                     await page.wait_for_timeout(1000)
                     # Re-locate upload_item after opening
                     upload_item = page.locator("div[data-role='menuitem']").filter(has_text="Upload list").first
                
                if not await upload_item.is_visible():
                    print("      ❌ 'Upload list' item not visible in menu. (Are you logged in?)")
                    await page.screenshot(path="debug_menu_error.png")
                    raise Exception("Upload list menu item not found.")

                print("   Selecting 'Upload list...'")
                # Dismiss modals one last time before clicking upload
                await dismiss_modals(page)
                
                try:
                    async with page.expect_file_chooser(timeout=15000) as fc_info:
                        # Robust click on "Upload list"
                        await upload_item.click(force=True)
                except:
                    print("      ⚠️ File chooser didn't appear. Trying an alternative click approach...")
                    await dismiss_modals(page)
                    async with page.expect_file_chooser(timeout=10000) as fc_info:
                        await page.keyboard.press("Enter") # Sometimes Enter on focused item works better
                
                print("   Waiting for file chooser...")
                file_chooser = await fc_info.value
                await file_chooser.set_files(file_path)
                
                print(f"   ✅ Uploaded {filename}")
                await page.wait_for_timeout(2000)
                
            except Exception as e:
                print(f"   ❌ Failed to import {base_name}: {e}")
                print("   📸 Saving screenshot to debug...")
                try:
                    await page.screenshot(path=f"debug_error_{base_name}.png")
                    print(f"      Saved: debug_error_{base_name}.png")
                except:
                    pass
                # Recover
                await page.keyboard.press("Escape")
        
        print("🏁 Sync Complete!")
        
        # Check if running in pipeline mode (Auto-close)
        if pipeline_mode or "--pipeline" in sys.argv:
            print("🤖 Pipeline Mode: Closing in 3 seconds...")
            await page.wait_for_timeout(3000)
            await context.close()
        else:
            # Manual Mode: Keep open
            print("👤 Manual Mode: Browser will remain open.")
            print("👉 Press Ctrl+C in this terminal to close browser and exit.")
            await asyncio.Future() 

    except Exception as e:
        print(f"❌ Critical Error in sync process: {e}")

if __name__ == "__main__":
    try:
        asyncio.run(run_sync())
    except KeyboardInterrupt:
        print("\n👋 Exiting...")
