"""Doc 21 (RS / Auto-Sector) — a third consumer of the sector database.

The page is in good shape: the three detection tiers match the file, and section 06
already carries the decoupled 25/10/7 calibration and the origin-preserving mapping.

The gap is in section 12, and it is the page's own rule turned on itself. §12 says
"re-export the sector table after any change to the sector database, or this pane and the
dashboard will disagree". True — but there are now THREE Pine consumers of that database,
generated by two different commands, and one of them needs a manual library publish before
the change reaches a chart at all.

  sectors.db  (stock_sector, 684 rows — the single source of truth)
     |
     +-- sector_manager.py export-pine <file>   -> the DB_LOOKUP block in this pane
     +-- gen_sector_map.py                      -> S4Core.sectorOf, read by S4
                                                   (then S4Core must be PUBLISHED)

Verified: sector_manager.DATA_DIR is the module directory, so both generators read the
same sectors.db — the risk is not two databases, it is one database and two artefacts that
can be regenerated at different times. gen_sector_map.py dedupes on a precedence rule
(user_* > NSE: index > curated > auto) and prints its collisions, so the two artefacts can
also legitimately differ on a conflicted symbol.
"""
import io

P = "docs_audit/pages/21_rs_autosector.html"
h = io.open(P, encoding="utf-8").read()
orig = h

anchor = ("      <li><b>Re-export the sector table</b> after any change to the sector database, "
          "or this pane\n      and the dashboard will disagree about which group a name belongs to.</li>")

if h.count(anchor) != 1:
    # the source wraps unpredictably; fall back to a single-line probe
    import re
    m = re.search(r'<li><b>Re-export the sector table</b>.*?</li>', h, re.S)
    assert m, "re-export bullet not found"
    anchor = m.group(0)

addition = anchor + '''
      <li><b>Regenerate <em>both</em> Pine sector maps, not just this one.</b> The database
      feeds two independently generated artefacts — the lookup block in this pane, and the
      packed map inside the shared library that the entry trigger reads. They are produced by
      different commands, so re-running one leaves the other on yesterday's mapping.</li>'''

h = h.replace(anchor, addition)

note_anchor = '<h2><span class="n">13</span>What it deliberately will not do</h2>'
assert h.count(note_anchor) == 1, "section 13 anchor not unique"

note = '''  <div class="note">
    <span class="tag">One database, two artefacts, and a publish step in between</span>
    <p><code>sectors.db</code> is the single source of truth — <b>684 mappings</b> in
    <code>stock_sector</code>, and the only file worth hand-editing. Everything downstream of it
    is generated and should never be edited in place.</p>
    <div class="tw"><table>
      <thead><tr><th>Artefact</th><th>Regenerated by</th><th>Reaches a chart when</th></tr></thead>
      <tbody>
        <tr><td>This pane's lookup block</td><td class="m">sector_manager.py export-pine &lt;file&gt;</td><td>you recompile this script</td></tr>
        <tr><td>The shared library's packed map</td><td class="m">gen_sector_map.py</td><td>you recompile <em>and</em> <b>publish a new library version</b></td></tr>
      </tbody>
    </table></div>
    <p><b>The publish is the step that gets forgotten.</b> A library compiles cleanly against
    your local edit while every script importing it still pins the old published version — so
    the change looks applied on the library's own tab and has not moved anywhere else. The
    symptom is a sector label that is right in this pane and stale on the entry trigger.</p>
    <p>The two artefacts can also differ <em>legitimately</em>: the packed map dedupes on a
    precedence rule — a hand-set mapping beats an index membership, which beats a curated one,
    which beats an inferred one — and prints each collision it resolves. Read that output. A
    symbol that appears there is one where the database itself holds two answers, and the fix
    belongs in the database, not in either generated file.</p>
  </div>

  ''' + note_anchor

h = h.replace(note_anchor, note)

assert h != orig
io.open(P, "w", encoding="utf-8").write(h)
print(f"Doc 21: {len(orig)} -> {len(h)} chars")
